### ISSUE TITLE
getLastCudaError() CUDA error : KernelError : (500) named symbol not found.

### ISSUE THREAD

**Issue by sr71684** [fatlipp/cuda-tree#1]
Hello,

epic library, thanks for providing such a great resource. 

Am trying to run the code, and run into this error:
```
/tmp/cuda-tree/cmake-build-debug/app/cuda_tree_app_obj /tmp/cuda-tree/app/config/AppConfig.json
Load Model()
WARN: Material file [ 12140_Skull_v3_L2.mtl ] not found.
Failed to load material file(s). Use default material.

# of vertices  = 40062
# of normals   = 40062
# of texcoords = 42682
# of shapes    = 4
bmin = -15.487700, 0.050200, -9.920400
bmax = 13.964300, 27.575899, 9.919900
RunAppOctree(): 240048
Initialize() capacity: 240048
 duration: 0
Reset()
Build()
/tmp/cuda-tree/lib/core/octree/OctreeBuilderCuda.cu(57) : getLastCudaError() CUDA error : KernelError : (500) named symbol not found.

Process finished with exit code 1
```

I noticed `#include <thirdparty/tinyobjloader/tiny_obj_loader.h>` was missing so am using this version `https://github.com/tinyobjloader/tinyobjloader/releases/tag/v2.0-rc1`

Any ideas?

**Comment by fatlipp** [comment]
Hello! Thank you for utilizing this project.
I'll investigate why **tiny_obj_loader** isn't being uploaded.

Regarding your issue: 
I suspect you need to specify **CUDA_ARCHITECTURES** in **./cuda-tree/lib/CMakeLists.txt** based on your environment and GPU. For example "52"

Or try to set CUDA_ARCHITECTURES **"OFF"** - it prevents CMake from generating an optimized code for any specific GPU architecture.

**Comment by fatlipp** [comment]
You can pull new changes from the master branch and set a new CMake flag:
cmake .. -DCUDA_ARCH=SET_YOUR_ARCH

If you skip this flag, it will be set to OFF

Also added `tiny_obj_loader.h`
